#+title: README
#+author: neckoPecker
#+options: toc:nil

* About
This is my custom emacs configuration. There are many like it, but this one is mine, and it could be yours too!

It's a bit bold to say this is really /mine/, because it's  just a whole bunch of cool configuration tweaks I found online.

* Installation
First, you need to install emacs on your system. I use Arch Linux, so I would install it with

#+begin_src bash
  sudo pacman -S emacs
#+end_src

After you have installed emacs, just clone this repository into your home directory (=git clone https://github.com/neckoPecker/.emacs.d=).

Then start up Emacs. It will automatically install the necessary packages you need (Don't worry about the =use-package= errors; they're normal).

* Configuration
You can directly edit the =init.el= file to change configurations that you don't like. However, if you plan to pull a new change that I made, you may have to fix git differences.

Alternatively (and preferably), you can make a =custom.el= file in your emacs configuration folder. 
You can copy the below in your =custom.el= file and change it however you like. 

#+begin_src emacs-lisp
;;; custom.el
;;; Commentary: 
;;
;; An example custom.el file to run along with init.el
;;

;;; Code:
;;;; Set backup directory
(setq backup-directory-alist '(("." . "~/.emacs.d/file-backups")))

;;; custom.el ends here
#+end_src

* Why?
My emacs configuration is very personalized, and so it caters to what I need. In essence, the whole goal of this configuration is to improve my learning and productivity.

* Credits
  
  + [[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org][Angry Bacon's dotemacs (Git Repository)]]
  + [[https://emacs.stackexchange.com/questions/3143/can-i-use-org-mode-to-structure-my-emacs-or-other-el-configuration-file][Lee H - "Can I use org-mode to structure my .emacs or other .el configuration file?" (StackExchange)]]
  + [[https://github.com/rougier/elegant-emacs][Rougier's Elegant Emacs (Github Repository)]]
