#+title: README
#+author: neckoPecker
#+options: toc:nil

* About
This is my custom emacs configuration. There are many like it, but this one is mine, and it could be yours too!

It's a bit bold to say this is really /mine/, because it's  just a whole bunch of cool configuration tweaks I found online.

* Installation
First, you need to install emacs on your system. I use Arch Linux, so I would install it with

#+begin_src bash
  sudo pacman -S emacs
#+end_src

After you have installed emacs, just clone this repository into your home directory (=git clone https://github.com/neckoPecker/.emacs.d=).

Then start up Emacs. It will automatically install the necessary packages you need (Don't worry about the =use-package= errors; they're normal).

* Why?
My emacs configuration is very personalized, and so it caters to what I need. In essence, the whole goal of this configuration is to improve my learning and productivity.

* Credits
  
  + [[https://github.com/angrybacon/dotemacs/blob/master/dotemacs.org][Angry Bacon's dotemacs (Git Repository)]]
  + [[https://emacs.stackexchange.com/questions/3143/can-i-use-org-mode-to-structure-my-emacs-or-other-el-configuration-file][Lee H - "Can I use org-mode to structure my .emacs or other .el configuration file?" (StackExchange)]]
